-- vim.pack.add {
--   'https://github.com/yetone/avante.nvim',
--   'https://github.com/nvim-treesitter/nvim-treesitter',
--   'https://github.com/stevearc/dressing.nvim',
--   'https://github.com/nvim-lua/plenary.nvim',
--   'https://github.com/MunifTanjim/nui.nvim',
--   'https://github.com/echasnovski/mini.pick',
--   'https://github.com/nvim-telescope/telescope.nvim',
--   'https://github.com/hrsh7th/nvim-cmp',
--   'https://github.com/ibhagwan/fzf-lua',
--   'https://github.com/nvim-tree/nvim-web-devicons',
--   'https://github.com/HakonHarnes/img-clip.nvim',
--   'https://github.com/MeanderingProgrammer/render-markdown.nvim',
-- }
-- vim.api.nvim_create_autocmd('PackChanged', {
--   group = vim.api.nvim_create_augroup('custom-avante-build', { clear = true }),
--   callback = function(ev)
--     local data = ev.data
--     if not data or not data.spec or data.spec.name ~= 'avante.nvim' then return end
--     if data.kind ~= 'install' and data.kind ~= 'update' then return end
--     if vim.fn.executable 'make' ~= 1 then return end
--
--     local result = vim.system({ 'make' }, { cwd = data.path }):wait()
--     if result.code ~= 0 then
--       local stderr = result.stderr or ''
--       local stdout = result.stdout or ''
--       local output = stderr ~= '' and stderr or stdout
--       if output == '' then output = 'No output from build command.' end
--       vim.notify(('Build failed for avante.nvim:\n%s'):format(output), vim.log.levels.ERROR)
--     end
--   end,
-- })
--
-- local ok_img_clip, img_clip = pcall(require, 'img-clip')
-- if ok_img_clip then
--   img_clip.setup {
--     default = {
--       embed_image_as_base64 = false,
--       prompt_for_file_name = false,
--       drag_and_drop = {
--         insert_mode = true,
--       },
--       use_absolute_path = true,
--     },
--   }
-- end
--
-- require('avante').setup {
--   behaviour = {
--     -- enable_cursor_planning_mode = true, -- enable cursor planning mode!
--   },
--   provider = 'claude',
--   providers = {
--     claude = {
--       endpoint = 'https://api.anthropic.com',
--       model = 'claude-sonnet-4-20250514',
--       timeout = 30000,
--       disable_tools = true,
--       extra_request_body = {
--         temperature = 0.75,
--         max_tokens = 20480,
--       },
--     },
--     claude_sonnet_with_tools = {
--       __inherited_from = 'claude',
--       disable_tools = false,
--     },
--     claude_opus = {
--       __inherited_from = 'claude',
--       model = 'claude-opus-4-20250514',
--     },
--   },
--   custom_tools = function()
--     local ok_mcphub, avante_ext = pcall(require, 'mcphub.extensions.avante')
--     if not ok_mcphub then return {} end
--     return { avante_ext.mcp_tool() }
--   end,
-- }
